- name: Install Nginx and Jenkins
  hosts: webservers
  become: yes
  become_user: root

  tasks:
    - name: Update APT Package Cache
      apt:
        update_cache: yes

    - name: Install Nginx and Jenkins
      apt:
        name: nginx
        state: present

    - name: Configure Nginx Document Root
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/sites-available/default
      notify:
        - Reload Nginx

    - name: Change ownership of web folder
      shell: |
        chown -R jenkins:jenkins /var/www/html


  handlers:
    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded
